#! /usr/bin/env ruby

ROOT = File.join(File.dirname(__FILE__), '..')

require File.join(ROOT, 'lib/squarebot')

while true
  begin
    directories = []
    directories << File.join(ROOT, 'lib', 'plugins')
    directories << File.join(ROOT, 'secret') if File.exists?(File.join(ROOT, 'secret'))
    bot = Squarebot::Bot.new(File.join(ROOT, 'config.yml'), directories)
    bot.run
  rescue SystemExit, Interrupt
    puts "exiting..."
    exit 0
  rescue Exception => ex
    puts "hit exception: #{ex.message}, #{ex.backtrace}"
    puts "sleeping for 10 seconds before restarting"
    sleep 10
    puts "starting again"
  end
end